version: '3.1'

services:
  springboot:
    image: syednayeempashakhadri/spring-boot-mongo:latest
    restart: always #This Will be Ignored If We Deploy in Docker Swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=production
    - MONGO_DB_PASSWORD=production@123
    ports:
    - 8080:8080
    working_dir: /opt/app
    depends_on:
    - mongo
    networks:
    - springappnetwork
    deploy:  #This Will be Considered only in Docker Swarm
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=production
    - MONGO_INITDB_ROOT_PASSWORD=production@123
    volumes:
    - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork

volumes:
  mongodb:
    external: true

networks:
  springappnetwork:

    external: true
