version: '3.1'

services:
  springboot:
    image: syednayeempashakhadri/spring-boot-mongo:latest
    # We remove 'restart: always' as it's redundant when 'deploy' is defined for swarm
    environment:
    # --- These are the credentials the Spring Boot application will use ---
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=production
    - MONGO_DB_PASSWORD=production@123
    ports:
    - 8080:8080
    working_dir: /opt/app
    depends_on:
    - mongo
    networks:
    - springappnetwork
    deploy:
      # Removed 'replicas', 'update_config', 'restart_policy' for clarity if not using swarm,
      # but keeping them here if you intend to run in swarm mode later.
      # If running with 'docker compose up', these are ignored.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    restart: always

  mongo:
    image: mongo
    environment:
    # --- IMPORTANT FIX: Use a separate name for the initial root user ---
    # This user is created with administrative privileges when the container starts.
    - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    - MONGO_INITDB_ROOT_PASSWORD=adminpass
    # The application user ('production') will now be created manually by the admin.
    volumes:
    - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork

volumes:
  mongodb:
    external: true

networks:
  springappnetwork:
    external: true
